// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewArticle struct {
	Title  string `json:"title"`
	UserID string `json:"userId"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
